# .github/workflows/test.yml
name: Run Tests

on:
  pull_request:

jobs:
  test:
    name: hogehoge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: ls
